// <auto-generated />
using System;
using HolidayPlanner.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HolidayPlanner.DataAccess.Migrations
{
    [DbContext(typeof(HolidayPlannerDbContext))]
    partial class HolidayPlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HolidayPlanner.DataModel.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DirectMangerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectMangerId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HolidayPlanner.DataModel.HolidayRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("HolidayTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("HolidayTypeId");

                    b.ToTable("HolidayRequests");
                });

            modelBuilder.Entity("HolidayPlanner.DataModel.HolidayType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acronym")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HolidayTypes");
                });

            modelBuilder.Entity("HolidayPlanner.DataModel.Employee", b =>
                {
                    b.HasOne("HolidayPlanner.DataModel.Employee", "DirectManger")
                        .WithMany()
                        .HasForeignKey("DirectMangerId");
                });

            modelBuilder.Entity("HolidayPlanner.DataModel.HolidayRequest", b =>
                {
                    b.HasOne("HolidayPlanner.DataModel.Employee", null)
                        .WithMany("HolidayRequests")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("HolidayPlanner.DataModel.HolidayType", "HolidayType")
                        .WithMany()
                        .HasForeignKey("HolidayTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
